spring:
 datasource:
  url: jdbc:mysql://localhost:3306/nttdata_microservicios_JoseMM?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  username: root
  password: jose2021
 jpa:
  hibernate:
   ddl-auto: create-drop
  database-platform: org.hibernate.dialect.MySQL5Dialect
  show-sql: true
  
  
 application:
  name: nttdata-ms-msschools-t1-JoseMM
 cloud:
  config:
   import-check:
    enabled: false
server:
 port: 8081
eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka/
