server:
 port: 9090

eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka

spring:
 application:
  name: gateway-service
 cloud:
  gateway:
   routes:
   - id: formacionMS1
     uri: http://127.0.0.1:8080
     predicates:
     - Path=/getStudentsInfo/**
   - id: formacionMS2
     uri: http://127.0.0.1:8081
     predicates:
     - Path=/getSchoolsInfo/**

